[profile.default]
src    = "src"
out    = "out"
libs   = ["lib"]
test   = "test"
script = "script"
solc   = "0.8.20"

[rpc_endpoints]
sepolia  = "${SEPOLIA_RPC_URL}"
mainnet  = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
